# Generated by Django 4.1 on 2022-09-30 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("EmpresaAfiliada", "0001_initial"),
        ("Solicitud", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComprobantePago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CP", "Comprobante de Pago"),
                            ("CB", "Certificación Bancaria"),
                            ("CE", "Cédula"),
                            ("CL", "Certificación Laboral"),
                        ],
                        max_length=2,
                    ),
                ),
                ("idComprobante", models.CharField(max_length=50)),
                ("destinatario", models.CharField(max_length=50)),
                ("cantidad", models.FloatField()),
                ("ciudad", models.CharField(max_length=50)),
                ("fecha", models.DateField()),
                ("direccion", models.CharField(max_length=50)),
                (
                    "empresaComprobante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EmpresaAfiliada.empresaafiliada",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Solicitud.solicitud",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CertificacionLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CP", "Comprobante de Pago"),
                            ("CB", "Certificación Bancaria"),
                            ("CE", "Cédula"),
                            ("CL", "Certificación Laboral"),
                        ],
                        max_length=2,
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("numCedula", models.CharField(max_length=15)),
                ("lugarExpedicion", models.CharField(max_length=100)),
                ("salario", models.FloatField()),
                ("terminoContrato", models.CharField(max_length=100)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EmpresaAfiliada.empresaafiliada",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Solicitud.solicitud",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CertificacionBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CP", "Comprobante de Pago"),
                            ("CB", "Certificación Bancaria"),
                            ("CE", "Cédula"),
                            ("CL", "Certificación Laboral"),
                        ],
                        max_length=2,
                    ),
                ),
                ("tipoDocumento", models.CharField(max_length=30)),
                ("numDocumento", models.CharField(max_length=15)),
                ("medioEnvio", models.CharField(max_length=30)),
                ("correo", models.CharField(max_length=30)),
                ("destinatario", models.CharField(max_length=50)),
                ("bancoCuenta", models.CharField(max_length=50)),
                ("tipoCuenta", models.CharField(max_length=30)),
                ("numeroCuenta", models.CharField(max_length=30)),
                (
                    "solicitud",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Solicitud.solicitud",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cedula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CP", "Comprobante de Pago"),
                            ("CB", "Certificación Bancaria"),
                            ("CE", "Cédula"),
                            ("CL", "Certificación Laboral"),
                        ],
                        max_length=2,
                    ),
                ),
                ("nombres", models.CharField(max_length=50)),
                ("apellidos", models.CharField(max_length=50)),
                ("numero", models.CharField(max_length=50)),
                ("fechaNacimiento", models.DateField()),
                ("lugarNacimiento", models.CharField(max_length=50)),
                ("sexo", models.CharField(max_length=1)),
                (
                    "solicitud",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Solicitud.solicitud",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
