# Generated by Django 4.1 on 2022-09-30 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Documento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificacionLaboral",
            fields=[
                (
                    "documento_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Documento.documento",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("numCedula", models.CharField(max_length=15)),
                ("lugarExpedicion", models.CharField(max_length=100)),
                ("salario", models.FloatField()),
                ("terminoContrato", models.CharField(max_length=100)),
            ],
            bases=("Documento.documento",),
        ),
    ]
