# Generated by Django 4.1 on 2022-09-30 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Documento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cedula",
            fields=[
                (
                    "documento_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Documento.documento",
                    ),
                ),
                ("nombres", models.CharField(max_length=50)),
                ("apellidos", models.CharField(max_length=50)),
                ("numero", models.CharField(max_length=50)),
                ("fechaNacimiento", models.DateField()),
                ("lugarNacimiento", models.CharField(max_length=50)),
                ("sexo", models.CharField(max_length=1)),
            ],
            bases=("Documento.documento",),
        ),
    ]
