# Generated by Django 4.1 on 2022-09-30 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Solicitud", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CP", "Comprobante de Pago"),
                            ("CB", "Certificación Bancaria"),
                            ("CE", "Cédula"),
                            ("CL", "Certificación Laboral"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Solicitud.solicitud",
                    ),
                ),
            ],
        ),
    ]
