# Generated by Django 4.1 on 2022-09-30 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Solicitud", "0001_initial"),
        ("Documento", "0002_cedula_certificacionlaboral_delete_documento"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificacionBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CP", "Comprobante de Pago"),
                            ("CB", "Certificación Bancaria"),
                            ("CE", "Cédula"),
                            ("CL", "Certificación Laboral"),
                        ],
                        max_length=2,
                    ),
                ),
                ("tipoDocumento", models.CharField(max_length=30)),
                ("numDocumento", models.CharField(max_length=15)),
                ("medioEnvio", models.CharField(max_length=30)),
                ("correo", models.CharField(max_length=30)),
                ("destinatario", models.CharField(max_length=50)),
                ("tipoCuenta", models.CharField(max_length=30)),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Solicitud.solicitud",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
