# Generated by Django 4.1 on 2022-09-30 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("EmpresaAfiliada", "0001_initial"),
        ("Solicitud", "0001_initial"),
        ("Documento", "0003_certificacionbancaria"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComprobantePago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CP", "Comprobante de Pago"),
                            ("CB", "Certificación Bancaria"),
                            ("CE", "Cédula"),
                            ("CL", "Certificación Laboral"),
                        ],
                        max_length=2,
                    ),
                ),
                ("idComprobante", models.CharField(max_length=50)),
                ("destinatario", models.CharField(max_length=50)),
                ("cantidad", models.FloatField()),
                ("ciudad", models.CharField(max_length=50)),
                ("fecha", models.DateField()),
                ("direccion", models.CharField(max_length=50)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EmpresaAfiliada.empresaafiliada",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Solicitud.solicitud",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
