# Generated by Django 4.1 on 2022-09-30 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("EmpleadoAfiliado", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.FloatField()),
                ("fechaPago", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("AP", "Aprobado"),
                            ("RP", "Reprobado"),
                            ("RE", "Reintente subiendo documentos más fiables"),
                        ],
                        default="RP",
                        max_length=2,
                    ),
                ),
                (
                    "empleadoAfiliado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EmpleadoAfiliado.empleadoafiliado",
                    ),
                ),
            ],
        ),
    ]
